// Generates components/icons.tsx from Boxicons regular (outline) SVGs.
// Edit MAP, then `pnpm --filter @pp/web gen:icons`. Never edit icons.tsx by hand.
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const SRC = join(root, "node_modules/boxicons/svg/regular");

const MAP = {
  Search: "search", Plus: "plus", Refresh: "refresh", History: "history",
  ChevronDown: "chevron-down", ChevronLeft: "chevron-left", ChevronRight: "chevron-right",
  Check: "check", X: "x", Sun: "sun", Moon: "moon", Globe: "globe", Calendar: "calendar",
  Filter: "filter", Image: "image", ImageLost: "image-alt", LinkExternal: "link-external",
  ErrorCircle: "error-circle", InfoCircle: "info-circle", CheckCircle: "check-circle",
  Trash: "trash", Edit: "edit", Grid: "grid-alt", Pulse: "pulse", Analyse: "analyse",
  Cog: "cog", ArrowBack: "arrow-back", Dollar: "dollar", Time: "time", Flag: "flag",
  TrendingUp: "trending-up", TrendingDown: "trending-down", Download: "download",
  Layer: "layer", BarChart: "bar-chart", LineChart: "line-chart", Link: "link", ListUl: "list-ul",
  Store: "store", Tag: "tag", Loader: "loader", Bell: "bell", Menu: "menu", Cart: "cart",
  Package: "package", Sort: "sort-alt-2", Star: "star", Yen: "yen", Category: "category",
  LogIn: "log-in", LogOut: "log-out", Lock: "lock-alt", Dots: "dots-horizontal-rounded",
  TestTube: "test-tube", Key: "key", Server: "server", Collection: "collection",
};

let out = `// GENERATED by scripts/gen-icons.mjs from boxicons/svg/regular — do not edit by hand.
import type { SVGProps } from "react";

export type IconProps = { size?: number; label?: string } & Omit<SVGProps<SVGSVGElement>, "children">;

function make(paths: string[]) {
  return function Icon({ size = 18, label, ...rest }: IconProps) {
    const a11y = label ? { role: "img", "aria-label": label } : { "aria-hidden": true as const };
    return (
      <svg width={size} height={size} viewBox="0 0 24 24" fill="currentColor" focusable="false" {...a11y} {...rest}>
        {paths.map((d, i) => <path key={i} d={d} />)}
      </svg>
    );
  };
}

`;
for (const [name, file] of Object.entries(MAP)) {
  const svg = readFileSync(join(SRC, `bx-${file}.svg`), "utf8");
  // circles become arc paths so every icon is a list of <path d>
  const ds = [...svg.matchAll(/<(path|circle)\b([^>]*)\/?>/g)].map(([, tag, attrs]) => {
    const a = (k) => attrs.match(new RegExp(`\\s${k}="([^"]+)"`))?.[1];
    if (tag === "path") return a("d");
    const [cx, cy, r] = ["cx", "cy", "r"].map((k) => Number(a(k)));
    return `M${cx - r} ${cy}a${r} ${r} 0 1 0 ${2 * r} 0a${r} ${r} 0 1 0 ${-2 * r} 0z`;
  });
  if (!ds.length) throw new Error(`no <path d> in bx-${file}.svg`);
  out += `export const ${name}Icon = make(${JSON.stringify(ds)});\n`;
}
writeFileSync(join(root, "components/icons.tsx"), out);
console.log(`icons.tsx: ${Object.keys(MAP).length} icons`);
